### ISSUE TITLE
Starting the Main

### ISSUE THREAD

**Issue by carlfm01** [omerjerk/RemoteDroid#12]
How I can start the main and get the methods by reflectiong to start injecting events?

**Comment by omerjerk** [comment]
Copying the email here in case someone wants the answer -

I'm assuming you read my blog post before emailing me. The command to start Main class is already listed in my other blog post - 
https://omerjerk.in/index.php/2015/10/16/execute-android-java-code-as-a-root-user/

It's basically as follows:

su -c "CLASSPATH=/data/app/in.omerjerk.remotedroid.app/base.apk /system/bin/app_process32 /system/bin in.omerjerk.remotedroid.app.Main optionalArgs"

In my case, I needed to execute the code as root. However, if you just need to create touch events, you can replace **su** with **sh**. If you are starting your Main class from outside using adb, you can do the following -

```adb shell <above command>```

**Comment by carlfm01** [comment]
Thanks @omerjerk  It worked, I just removed the 32 from app_process.


Get the CLASSPATH by running  adb shell pm path {package name}

My command without root looks like
 adb shell sh -c 'CLASSPATH=/data/app/neoxzim.com.adbtest-1.apk /system/bin/app_process /system/bin neoxzim.com.adbtest.Main'
